### ISSUE TITLE
Better GUI for invitations and submissions

### ISSUE THREAD

**Issue by guaraqe** [guaraqe/csdc#23]
Invitations and submissions should be entered in an appropriated form, with some rich-text capabilities (markdown?). As such, it should be independent from the unit/person page. Depends on #9.

**Comment by guaraqe** [comment]
Since #9 is closed, and the basic actions for submissions and invitations is implemented, I have to think better about the user interface. The current interface works, but it is far from ideal and will lead to a bad experience.

I think the following would give a better experience:

- Both people and units should have an _Actions_ menu that allows to invite or submit to them, as necessary.

- This screen would be different from the visualization one, and would allow to set the message.

The following steps are necessary:

- [ ] Implement a base page for submissions.
- [ ] Implement a base page for invitations.
- [ ] Implement a dropdown menu to take to these images from both users and units.

I think that after this is ready, the basic utilities of the system will be ready, and I will be able to proceed to a production setup.

**Comment by paulbourgine** [comment]
Bonjour Juan,

Nous allons utiliser WordPress responsive avec une interface wysiwyg .. pour les questionnaires des pages WordPress.

La base de données qui nous va le mieux serait Neo4J (non SQL) avec une interface Haskell (hasbolt par exemple). 
Plus généralement, n'importe quelle DB SQL avec une même interface Haskell (Persistent va pour SQL et non-SQL: qu'en  penses-tu?)

Je suis prêt à travailler aussi en Haskell (et Linda aussi)

Réponds moi vite ..

Amitiés,
Paul
