### ISSUE TITLE
Units should be deletable

### ISSUE THREAD

**Issue by guaraqe** [guaraqe/csdc#27]
A conservative take on this would to only allow units that only have one person (the chair) on it to be destroyed. This would allow clicking errors to be solved quickly.

**Comment by paulbourgine** [comment]
The case of only one person is generally the case when a chair is  asking someone to create a new sub e-team. Thus your rule is not for beginning of life of a unit but its ('momentary') end-of-life.
The important point is to create 'the past history of the e-campus' for keeping memory of all units and  the possibility to reactivate them with their challenge. (other case: a unit without external link)
