### ISSUE TITLE
Improve the left menu

### ISSUE THREAD

**Issue by itytophile** [guaraqe/csdc#43]
The left menu's behavior is not intuitive. We can delete the "View units" / "View person" items which are strange.

**Comment by guaraqe** [comment]
My original idea was to have:
- Menu entries
- "Tabs", for entities that you are look at, such as people and units. These tabs would appear after the menu, in a separate section, and would be closeable.
These current menu entries are an approximation of that where you always have a tab of given type open, that changes state when needed.

We definitely have to do that later.

**Comment by itytophile** [comment]
So you want something like a history of the pages you visited ? Like if I visit the "President page", a tab "President" will be displayed in the left menu ?

**Comment by guaraqe** [comment]
Not really a history, but I think we should make possible to look at more than one page at the same time. But maybe a better choice is just to use links correctly and use multiple browser tabs. To be discussed.
