### ISSUE TITLE
Use a CSS Framework ?

### ISSUE THREAD

**Issue by itytophile** [guaraqe/csdc#44]
We can use a CSS Framework to have some already made components. This will give the website a more modern look and feel.
We can use [Bulma](https://bulma.io/) which doesn't come with any JS so we can still have a pure Elm app.

**Comment by guaraqe** [comment]
This can be a good idea for the near future, let's reach feature completion and thing about this after. `elm-ui` is very easy to use, so it's nice for sketching (specially since it abstracts all the margin, etc, etc)>
