### ISSUE TITLE
some things must be unique and still are not

### ISSUE THREAD

**Issue by teamcsdc** [guaraqe/csdc#45]
in the unit viewer, we can see every links, links must be unique, actually a person can be seen more than one time in the viewer

**Comment by teamcsdc** [comment]
we can actually see more than one time a Unit in the Studio Unit panel

**Comment by guaraqe** [comment]
What do you mean more than one time a unit? It is possible for units to have the same name (I am not completely sure if that is a good idea or not), and you if you have multiple units with the same name, it will seem like it's the same multiple times.

Maybe names should be unique - to decide later.
