### ISSUE TITLE
Make the haskell-language-server work with the project while keeping Nix

### ISSUE THREAD

**Issue by itytophile** [guaraqe/csdc#46]
[haskell-language-server](haskell-language-server)
At the moment, the language server doesn't work with the project. It works out of the box with a Stack project.
There is 2 solutions:
- Find a way to make it work without Stack (only nix and cabal)
- Turn the project into a Stack project (we must modify the nix files)

**Comment by guaraqe** [comment]
There are solutions for HSL + Nix, but I never used it so I cannot recommend something now.

If Stack is working, keep using it, and I will try to setup the Nix solution when I have more time.

**Comment by itytophile** [comment]
#50
