### ISSUE TITLE
Implement invitations and submissions

### ISSUE THREAD

**Issue by guaraqe** [guaraqe/csdc#9]
Both interactions happen between a person and a unit:

- a unit can _invite_ a person to be part of it
- a person can _submit_ a proposal to be member of the unit

Both interactions contain a message and can be accepted or rejected, with a message. In case of an acceptation, the member becomes part of the unit.

The person who accepts or rejects from the part of the unit is the chair. This depends on #8.

**Comment by guaraqe** [comment]
I have implemented member submissions. Still missing:

- member invitations
- subpart messages

All of these depend on units doing actions. For the moment, the chair will be the one doing this. A good plan is:

- Users that are chairs should see invitation buttons on users and units.
- Units have an Inbox that is only accessible by the chair.

**Comment by paulbourgine** [comment]
Ma principale remarque: submission/invitation est uniforme entre individus et e-structures (représenté par leur chair). De plus après acceptation de l'autre, le lien est fait: les deux sont d'accord. Il peut être supprimé si l'un des deux n'est plus d'accord.
Si un noeud n'a plus de lien, il n'est pas supprimé: il reste dans l'ensemble des noeuds en attente.
Paul

**Comment by paulbourgine** [comment]
1. Each individual member has a 'studio' with all his roles (first column of its personalized FancyTree) for making actions corresponding to each role including the 'generic' actions like invitation/submission. When he starts any exploration of the Fancy tree for creating  a link, he does  that with a well defined role as chair including 'self' (chair of an individual is 'self'). 
3. when he clicks on a unit button,  it is asking for a link. And the chair has to accept or refuse.
4. the qualification 'invitation|submission' is just depending on  the respective level of the two  chairs. (Each "unit" has a level in the graph = minimum length of the path to the root; and individual have the maximum length)
What do you think?
